version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_raiox
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: mestre
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: raiox_backend
    restart: always
    ports:
      - "3001:3001"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=mestre
      - DB_PASSWORD=123456
      - DB_DATABASE=bdraiox
      - DB_PORT=3306
      - PACIENTES_DB_HOST=db
      - PACIENTES_DB_USER=mestre
      - PACIENTES_DB_PASSWORD=123456
      - PACIENTES_DB_DATABASE=corpore
      - PACIENTES_DB_PORT=3306
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    container_name: raiox_frontend
    restart: always
    stdin_open: true
    tty: true
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./frontend:/app

volumes:
  mysql_data:
